import { Geist, Geist_Mono, Bruno_Ace_SC, Bruno_Ace, Poppins } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import CustomCursor from "./components/CustomCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const brunoAceSC = Bruno_Ace_SC({
  variable: "--font-bruno-ace-sc",
  subsets: ["latin"],
  weight: "400",
});

const brunoAce = Bruno_Ace({
  variable: "--font-bruno-ace",
  subsets: ["latin"],
  weight: "400",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const centuryGothic = localFont({
  src: [
    {
      path: '../public/fonts/Century Gothic.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-century-gothic',
  fallback: ['Century Gothic', 'CenturyGothic', 'AppleGothic', 'sans-serif'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${brunoAceSC.variable} ${brunoAce.variable} ${centuryGothic.variable} ${poppins.variable}`}>
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
